name: Snapshot

on: push

jobs:
  snapshot:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      - name: node version
        run: node -v

      - name: Install
        run: yarn install

      - name: Snapshot
        run: yarn snapshot

  snapshot-image:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      - name: node version
        run: node -v

      - name: Install
        run: yarn install

      - name: Storybook Build
        run: yarn storybook:build

      - name: Snapshot Image
        run: yarn snapshot-image:static
