name: Snapshot

on: push

jobs:
  snapshot:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
          cache: yarn

      - name: node version
        run: node -v

      - name: Install
        run: yarn install

      - name: Snapshot
        run: yarn snapshot

  snapshot-image:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: docker-compose build

      - name: Install
        run: docker-compose run node yarn install

      - name: Storybook Build
        run: docker-compose run node yarn storybook:build

      - name: Snapshot Image
        run: docker-compose run node /bin/bash ./docker-scripts/snapshot-image-static.sh

      - name: Output diff
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: diff-output
          path: ./stories/__image_snapshots__/__diff_output__
